language: c
script: make examples
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libxfixes-dev
      - mesa-common-dev
      - libgl1-mesa-dev

matrix:
  include:
    - name: "Examples-release-rasberry-cross"
      language: c
      compiler: gcc
      before_install:
        - pushd /tmp
        - wget https://github.com/raspberrypi/tools/archive/master.tar.gz -O raspi-tools.tar.gz
        - tar xzf raspi-tools.tar.gz
        - wget https://github.com/raspberrypi/firmware/archive/master.tar.gz -O raspi-firmware.tar.gz
        - tar xzf raspi-firmware.tar.gz
        - popd
      script: make RASPBERRY=1 CROSS=1 RPI_TOOLS=/tmp/tools-master RPI_VCDIR=/tmp/firmware-master/hardfp/opt/vc examples
    - name: "Examples-release-win64"
      os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - msbuild.exe vs2015/examples.sln -p:Configuration=Release -p:Platform=x64 -t:examples
    - name: "Examples-release-win32"
      os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - msbuild.exe vs2015/examples.sln -p:Configuration=Release -p:Platform=x86 -t:examples
